-- Migration: Add SMTP settings to system_settings table
-- Date: 2026-10-09

ALTER TABLE system_settings
    ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_port INTEGER NOT NULL DEFAULT 587,
    ADD COLUMN IF NOT EXISTS smtp_username VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_password TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_from_email VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255) NOT NULL DEFAULT 'DatrixOps',
    ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(32) NOT NULL DEFAULT 'tls';
