-- Dashboard notifications generated by alert state transitions.
-- The migration is idempotent because the current backend reruns SQL files on startup.
CREATE TABLE IF NOT EXISTS dashboard_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    alert_rule_id UUID
        REFERENCES alert_rules(id)
        ON DELETE SET NULL,

    server_id UUID
        REFERENCES servers(id)
        ON DELETE SET NULL,

    kind VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}',
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- List newest notifications for one user.
CREATE INDEX IF NOT EXISTS idx_dashboard_notifications_user_created
    ON dashboard_notifications(user_id, created_at DESC);

-- Count unread notifications quickly for the bell badge.
CREATE INDEX IF NOT EXISTS idx_dashboard_notifications_user_unread
    ON dashboard_notifications(user_id, created_at DESC)
    WHERE read_at IS NULL;
